### PR TITLE
Adding Argo Rollouts object support for pod label selector

### PR DESCRIPTION
**Pull request by daftping**
# One-line summary
Adding support for [Argo Rollouts](https://argoproj.github.io/rollouts/)
https://github.com/zalando-incubator/kube-metrics-adapter/issues/682

## Description
kube-metrics-adapter supports only Deployment and StatefulSet controllers for label selector making it impossible to use it with any other controllers. Extending the label selector to support Argo Rollouts would people to adopt kube-metrics-adapter or allowed them to migrate to Argo Rollouts. 

## Types of Changes
- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by daftping** [comment]
Hello @mikkeloscar, may I ask you for a review, please?

**Comment by mikkeloscar** [comment]
@daftping I'm not familiar with the details of Argo Roll outs, can you please add an example of the use case this would support? E.g. example in the README.md like we have for all the collector types

**Comment by daftping** [comment]
@mikkeloscar Argo `Rollout` acts as a drop-in replacement for a `Deployment` resource and works with HPA in the same way as a `Deployment` does. Currently, the Pod Collector can only retrieve the label selector from `Deployment` and `StatefulSet` to identify the pods. This PR adds support for the `Rollout` object, allowing the Pod Collector to recognize pods managed by a `Rollout`.

The configuration example for integrating with HPA looks similar to that of a `Deployment`, with the primary difference being the `scaleTargetRef`:

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.pods.requests-per-second.json-path/json-key: "$.http_server.rps"
    metric-config.pods.requests-per-second.json-path/path: /metrics
    metric-config.pods.requests-per-second.json-path/port: "9090"
    metric-config.pods.requests-per-second.json-path/scheme: "https"
    metric-config.pods.requests-per-second.json-path/aggregator: "max"
    metric-config.pods.requests-per-second.json-path/interval: "60s" # optional
    metric-config.pods.requests-per-second.json-path/min-pod-ready-age: "30s" # optional
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: myapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: requests-per-second
      target:
        averageValue: 1k
        type: AverageValue
```
I have updated the documentation to explain this integration. Adding the same example with a different target seemed a bit too verbose to me, so I skipped it. However, if you feel it would be beneficial to include it, I would be happy to extend the README with an example.

**Comment by daftping** [comment]
Hey @mikkeloscar,

Following your feedback, I've added an explanation of how this integration works, aligning with the existing documentation style for collector types.

Could you please take another look at the changes and let me know if there's anything else that needs adjustment? I believe this feature could significantly benefit users looking to integrate Argo Rollouts with kube-metrics-adapter, and I'm keen on getting your feedback to ensure it aligns well with the project's standards and expectations.

Thank you for your time and consideration.

**Review by mikkeloscar — CHANGES_REQUESTED** [review]

**Comment by daftping** [comment]
Thank you @mikkeloscar for the review. I have updated the whole `pod_collector_test.go` to use Background context for consistency.
Please take a look.

**Review by mikkeloscar — APPROVED** [review]

**Comment by mikkeloscar** [comment]
:+1:

**Comment by daftping** [comment]
Looks like two approvals are required.
@katyanna do you mind reviewing this PR, please?

**Comment by katyanna** [comment]
👍

**Pull request merged**
