### PR TITLE
Adding test coverage

### PR DESCRIPTION
**Pull request by muaazsaleem**
# Adding Unit tests

> Issue : #6 (only if appropriate)

## Description
Adding test coverage to the codebase

## Types of Changes
_What types of changes does your code introduce? Keep the ones that apply:_

- Refactor/improvements

## Tasks
_List of tasks you will do to complete the PR_
- [x] Determine coverage of current codebase ( Integrate [coverall](https://coveralls.io/) )

## Review
_List of tasks the reviewer must do to review the PR_
- [ ] Approve

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@muaazsaleem I updated the go.sum file to work with go 1.11.2. Now it doesn't work with go 1.11.1 which seems to still be used on travis... IMO we can merge this and just wait for travis to catch up.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by muaazsaleem** [comment]
@mikkeloscar looks like explicitly bumping up the `go version` in `.travis.yml` worked

**Comment by arjunrn** [comment]
:+1:

**Comment by muaazsaleem** [comment]
👍

**Pull request merged**
