### PR TITLE
Add readme in gh-pages

### PR DESCRIPTION
**Pull request by prune998**
Signed-off-by: Sebastien Prune THOMAS <[prune@lecentre.net](mailto:prune@lecentre.net)>
# One-line summary

> [Issue : #1234 (only if appropriate)](https://github.com/zalando-incubator/kube-metrics-adapter/issues/431)

## Description
This PR is adding a readme with usage information for the Github Pages that is hosting the helm chart release.

## Types of Changes
_What types of changes does your code introduce? Keep the ones that apply:_

- Refactor/improvements
- Documentation / non-code

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@prune998 can you sign-off your commit (see the DCO check)

**Comment by prune998** [comment]
> @prune998 can you sign-off your commit (see the DCO check)

I guess it's OK, but you have to manually restart the check ?

**Comment by szuecs** [comment]
Can you please do
```
git rebase --signoff -i
```

remove all "Signed off" comments, but the last and `push -f`

**Comment by prune998** [comment]
Not sure what I'm doing wrong here :/

**Comment by mikkeloscar** [comment]
From the details link of the DCO check:

image


So it's a mismatch with your git author name/email and the sign-off name/email.

**Comment by prune998** [comment]
should be good now... Not sure why it was sticking to my WK email... whatever. Thanks for the help

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
