### PR TITLE
Expose basic go metrics via prometheus

### PR DESCRIPTION
**Pull request by linki**
Adds a prometheus endpoint serving basic Go metrics.

### CODE REVIEW

**Comment by arjunrn** [comment]
I'm not sure if this really adds any value than exposing go runtime metrics. I think we should also add a counter for successful metrics collection and failed ones.

**Comment by linki** [comment]
Added counter metrics for successful and erroneous attempts to collect metrics and update HPAs. This is how it looks:

```console
$ curl -sS localhost:7979/metrics | grep kube_metrics
# HELP kube_metrics_adapter_collections_error The total number of failed collection attempts
# TYPE kube_metrics_adapter_collections_error counter
kube_metrics_adapter_collections_error 1
# HELP kube_metrics_adapter_collections_success The total number of successful collections
# TYPE kube_metrics_adapter_collections_success counter
kube_metrics_adapter_collections_success 20
# HELP kube_metrics_adapter_updates_error The total number of failed HPA update attempts
# TYPE kube_metrics_adapter_updates_error counter
kube_metrics_adapter_updates_error 0
# HELP kube_metrics_adapter_updates_success The total number of successful HPA updates
# TYPE kube_metrics_adapter_updates_success counter
kube_metrics_adapter_updates_success 9
```

**Comment by mikkeloscar** [comment]
:+1:

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
