### PR TITLE
Update golangci-lint config

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update golangci-lint config. Remove legacy `deadcode` and `varcheck` linters.

Also fix formatting of one file.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by gargravarr** [comment]
I still see `varcheck` configured

**Comment by mikkeloscar** [comment]
> I still see varcheck configured

Thanks! I forgot to commit that change. It's fixed now!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
