### PR TITLE
Return a value when atleast one of the metrics returns a value

### PR DESCRIPTION
**Pull request by arjunrn**
The `MaxCollector` fails when even one of the metrics collector returns an error. But when other metrics are present it should just continue and return the max of the rest.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Should we add a unit test? :)

**Comment by muaazsaleem** [comment]
👍

**Comment by muaazsaleem** [comment]
👍

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
