### PR TITLE
Add a kubernetes helm chart

### PR DESCRIPTION
**Pull request by tanersener**
# Adds a kubernetes helm chart

> Issue : #56

## Description
Creates a helm chart for this project that can be installed using `helm install`.

## Types of Changes
- New feature (non-breaking change which adds functionality)
- Refactor/improvements

## Features
- Existing helm deployment files are preserved
- Helm chart is added under the `docs/helm` folder
    - Service account definition in `rbac.yaml` file is extracted as a separate `service-account.yaml` file
    - Missing `kube-metrics-adapter-resource-reader` cluster role binding is added
    - Definition names are updated with `kube-metrics-adapter` prefix
- Can be installed using `helm install`
- All docker image options except `--help` and `--bind-address` can be customized during `helm install`
- Allows changing the namespace
- Can be used to install a different docker image

## Deployment Notes
You can deploy the chart using the following command

`helm install kube-metrics-adapter helm --set prometheus.server=http://iamserver --set aws.region=eu-west1 --set prometheus.metricsAddress=:9090 --set zmon.tokenName=QTCuP5lwSQj6hdUrnGqAcYyspGY17U --set influxDB.address=http://influx --set log.level=2`

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@tanersener Thanks for this! As we don't use helm ourselves we can support this as best effort, but I would prefer if we also keep the existing non-helm resources in place. Could you change the PR to have both helm and non-helm manifests?

**Comment by tanersener** [comment]
@mikkeloscar Moved the `helm` folder under the `docs`. Now we have both manifests side by side.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Comment by tanersener** [comment]
Thanks :+1:

**Pull request merged**
